# Be sure to restart your server when you modify this file.
development:
  college_score_card_api_key: a8h91Nv6pZ2ErJrFE3fq9UqdQ5Dl4IgT1SL5ZUXf

test:
  college_score_card_api_key: a8h91Nv6pZ2ErJrFE3fq9UqdQ5Dl4IgT1SL5ZUXf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  college_score_card_api_key: <%= ENV["COLLEGE_SCORE_CARD_API_KEY"] %>
